config/routes.rb
Rails.application.routes.draw do

	root 'base#index'
	get 	'/about', 		to: 'base#about'

	get 	'/login',   	to: 'sessions#new'
	post 	'/login', 		to: 'sessions#create'
	get 	'/logout',  	to: 'sessions#destroy'

	get 	'/signup', 		to: 'users#new'

	resources :users, only: [:index, :show, :create] do
		member do
			get :friender, :friended
		end
	end

	resources :friendships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :friender, class_name: "User"
	belongs_to :friended, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, 	presence: true,
										length: { maximum: 15 }

	has_many :friendships, foreign_key: "friender_id", class_name: "Friendship"
	has_many :friended,    through: :friendships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/base_controller.rb
class BaseController < ApplicationController

	def index
	end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	include SessionsHelper
	include FriendshipsHelper

	def create
		@friendship = current_user.friendships.new(friendship_params)
		@friendship.accepted = false
		if @friendship.save
			# reverse friendship
			@friendship.friended.friendships.new(friended_id: current_user.id, 
																							accepted: false).save
			redirect_to @friendship.friended
		else
			render inline: "<h1>oh no</h1"
		end
	end

	def destroy
		friendship  = Friendship.find(params[:id])
		ex_friend   = friendship.friended
		friendship.destroy

		# reverse friendship
		friendship2 = Friendship.find_by(friended: current_user, friender: ex_friend)
		friendship2.destroy

		redirect_to ex_friend
	end

	private
		def friendship_params
			params.require(:friendship).permit(:friended_id)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(name: params[:session][:name]) # CHANGE THIS TO EMAIL
		if user
			# render inline: "<h1>found</h1>"
			log_in(user)
			redirect_to user
		else
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil # CHANGE THIS TO EMAIL
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include SessionsHelper
	include FriendshipsHelper
	# before_action :logged_in_user, except: [:new, :create]

	def index
		@users = User.all
	end

	def show
		@user  			= User.find(params[:id])
		@friendship = current_user.friendships.new
		@friends    = @user.friendships.where(accepted: true)
		@requests   = @user.friendships.where(accepted: false)
	end

	def new
		@user  = User.new
	end

	def create
		@user  = User.new(user_params)
		if @user.save
			redirect_to @user
		else
			render inline: "<h1>Oh no</h1>"
		end
	end

	private
		def user_params
			params.require(:user).permit(:name)
		end

		def logged_in_user
			unless logged_in?
				redirect_to login_path
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = "")
		if page_title.empty?
			"Fakebook"
		else
		  page_title
		end
	end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper

	def im_friend_of(user)
		return true if current_user.friendships.find_by(friended_id: user.id)
		return false
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user) # writes the session cookie
		session[:user_id] = user.id
	end

  def current_user
  	# if it exists there, take it and call it a day
  	if 		(user_id = session[:user_id]) 
  		@current_user ||= User.find(user_id)
      return @current_user
    else
      return nil
  	end
  	# for sessions, it will become more complex
  end

  def logged_in?
  	!current_user.nil?
  end
end

app/views/base/about.html.erb
<% provide(:title, "About") %>


<h1>About</h1>

<ul>
	<li>
		Postgresql has been used since the beginning in 
		<code>DEV</code> and <code>TEST</code> environments as well
	</li>
	<li>
		the whole application has been made with 
		<%= link_to "Test Driven Development", "https://en.wikipedia.org/wiki/Test-driven_development" %>	
	</li>
</ul>

app/views/base/index.html.erb
<% provide(:title, "Home") %>

<h1>Home</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div>
      	<%= link_to "home",				root_path %>
      	<%= link_to "All users", users_path %>
      </div>
      <div>
        <% if current_user != nil %>
          logged in as
          <%= link_to "#{@current_user.name}", @current_user %>
          <%= link_to "Logout",   logout_path %>
        <% else %>
          <%= link_to "Signup",   signup_path %>
          <%= link_to "Login",     login_path %>
        <% end %>       
      </div>
    </nav>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>

<h1>All Users</h1>

<ul>
	<% @users.each do |user| %>
		<li><%= link_to user.name, user %></li>
	<% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>

<h1>Sign Up</h1>

<%= form_for @user do |f| %>

	<%= f.label 		 :name %>
	<%= f.text_field :name %>

	<%= f.submit %>

<% end %>

app/views/users/show.html.erb
<% provide(:title, "#{@user.name}") %>

<h1><%= @user.name %></h1>

<% if im_friend_of(@user) %>
	<h2>
		<%= form_for(current_user.friendships.find_by(friended_id: @user.id),
				html: { method: :delete }) do |f| %>
			<%= f.submit("Unfriend") %>
		<% end %>
	</h2>
<% else %>
	<h2>
		<%= form_for(current_user.friendships.build) do |f| %>
			<%= f.hidden_field :friended_id, value: @user.id  %>
			<%= f.submit("Send a Friendship request") %>
		<% end %>
	</h2>
<% end %>

<h2><%= @requests.count %> Friendships Requests</h2>
<ul>
	<% @requests.all.each do |request| %>
		<li>
			<%= link_to request.friended.name, request.friended %>	
		</li>
	<% end %>
</ul>


<h2><%= @friends.count %> Friends</h2>
<ul>
	<% @friends.all.each do |friend| %>
		<li><%= link_to friend.friended.name, friend.friended %></li>
	<% end %>
</ul>